name: Build and Release

on:
  push:
    tags:
      - 'v*'



jobs:
  build-win:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Windows Exe
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=icon.ico --name "1440x3440-win" --add-data "app;app" viewer.py
    - name: Upload Windows Build
      uses: softprops/action-gh-release@v1
      with:
        files: dist/1440x3440-win.exe
